version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - copyloopvar
    - cyclop
    - dogsled
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errname
    - forcetypeassert
    - funcorder
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gosec
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - misspell
    - mnd
    - musttag
    - nestif
    - nilerr
    - noinlineerr
    - staticcheck
    - sqlclosecheck

  settings:
    copyloopvar:
      check-alias: true
    cyclop:
      max-complexity: 15
      package-average: 5
    dogsled:
      max-blank-identifiers: 1
    errcheck:
      check-type-assertions: true
      check-blank: true
      verbose: true
    gocyclo:
      min-complexity: 15
    ineffassign:
      check-escaping-errors: true
    mnd:
      ignored-numbers: 10
    nestif:
      min-complexity: 4